server:
  port: 9000
spring:
  application:
    name: rabbitmq-springboot
  rabbitmq:
    # web管理页面 http://39.106.115.236:15672/
    host: 39.106.115.236
    port: 5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: /mhs # 虚拟主机
    listener:
      simple:
        retry:
          # 是否失败重试，默认为false
          enabled: true
          # 最大重试次数
          max-attempts: 3
          # 重试次数间隔
          initial-interval: 3000
          # 重试时间间隔 乘子，如第一次3s，第二次则为6秒，第三次则为12s
          multiplier: 2

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 20
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1
        # 连接池中的最大空闲连接 默认为8
        max-idle: 10
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0

